version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  pipeline:
    build: .
    # TODO: change --queues=my-queue to --queues=my-pipeline-name
    command: poetry run celery -A run worker --loglevel=INFO --queues=my-queue
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
